Repository entando/pda-redhatpam-engine, pull requests merged in 2020-04, with the labels that each got.

#41 PDA-171 Fixed task attachment download filename
  src/main/java/org/entando/plugins/pda/pam/service/task/KieTaskAttachmentService.java
  src/main/java/org/entando/plugins/pda/pam/service/util/KieDocument.java
  src/test/java/org/entando/plugins/pda/pam/service/task/KieTaskAttachmentServiceTest.java
  src/test/java/org/entando/plugins/pda/pam/util/KieTaskTestHelper.java
Labels: approved, size/M

#42 PDA-168 Added tests and updated Postman Collection for Full Task Form Sample
  src/main/java/org/entando/plugins/pda/pam/service/process/KieProcessService.java
  src/test/java/org/entando/plugins/pda/pam/service/process/KieFormDeserializerTest.java
  src/test/java/org/entando/plugins/pda/pam/service/process/KieProcessFormServiceTest.java
  src/test/java/org/entando/plugins/pda/pam/service/task/KieTaskFormServiceTest.java
  src/test/java/org/entando/plugins/pda/pam/util/KieFormTestHelper.java
  src/test/java/org/entando/plugins/pda/pam/util/KieTaskFormTestHelper.java
  src/test/resources/form/full-kie-task-form-submission.json
  src/test/resources/form/full-task-form-submission.json
  src/test/resources/form/full-task-form.json
  src/test/resources/form/simple-kie-task-form-submission.json
  src/test/resources/form/simple-task-form-submission.json
  src/test/resources/form/simple-task-form.json
Labels: approved, size/XXL

#43 PDA-196: Fix table name to comply with MySQL
  src/main/resources/summary/datarepositories/cases.properties
  src/main/resources/summary/datarepositories/requests.properties
  src/test/resources/summary/datarepositories/datarepository1.properties
  src/test/resources/summary/datarepositories/datarepository2.properties
Labels: approved, size/S

#37 PDA-162 Testing Jenkins X integration
  README.md
Labels: approved, size/S
